name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        device:
          - "iPhone 8 (13.1)"
          - "iPhone 11 Pro Max (13.1)"
      fail-fast: false

    runs-on: macOS-latest
    steps:
      - name: "List all simulators"
        run: "xcrun instruments -s"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v6
