name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: nanasess/setup-chromedriver@master
      - run: chromedriver --port=4444 &
      
      - uses: subosito/flutter-action@v1
      
      - name: "Run Flutter Driver tests"
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze
        
      - uses: erickzanardo/flutter-gh-pages@v6
