name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run Android Emulator
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --list | grep system-images
          $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86_64"
          $ANDROID_HOME/tools/bin/avdmanager list avd
          $ANDROID_HOME/tools/bin/avdmanager create avd --force --name Nexus_5X --abi google_apis/x86_64 --package "system-images;android-29;google_apis;x86_64" --device "Nexus 5X"
          $ANDROID_HOME/tools/emulator -avd Nexus_5X -skin 1080x1920 &
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
      
      - name: "Run Flutter Driver tests"
        run: |
          flutter emulators --launch Nexus_5X
          sleep 50s
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze
        
      - uses: erickzanardo/flutter-gh-pages@v6
