name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    strategy:
      # A set of different configurations of the virtual
      # environment.
      matrix:
        device:
          - "iPhone 13 Pro"
      fail-fast: false
      # The type of machine to run the job on.
      # Contains a sequence of tasks.

    runs-on: macos-11
    steps:
      - name: run tests
        run: |
          set -eu

          # start android emulator
          START=`date +%s` > /dev/null

          $ANDROID_HOME/tools/android list avd
          $ANDROID_HOME/tools/emulator64-arm -avd test -no-window -no-boot-anim -no-audio -verbose &
          wait-for-emulator
          unlock-emulator-screen
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: "List devices"
        run: "flutter devices"
      - name: "List devices"
        run: "flutter pub get"
      - name: "Run Flutter Driver tests"
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -v"
      - uses: erickzanardo/flutter-gh-pages@v6
