name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    strategy:
      # A set of different configurations of the virtual
      # environment.
      matrix:
        device:
          - "iPhone 13 Pro"
      fail-fast: false
      # The type of machine to run the job on.
      # Contains a sequence of tasks.

    runs-on: macos-11
    steps:
      - name: "List all simulators"
        run: "xcrun simctl list"
      - name: "Start Simulator"
        run: xcrun simctl boot "iPhone 13 Pro"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: "List devices"
        run: "flutter devices"
      - name: "List devices"
        run: "flutter pub get"
      - name: "Run Flutter Driver tests"
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart"
      - uses: erickzanardo/flutter-gh-pages@v6
