name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    strategy:
      # A set of different configurations of the virtual
      # environment.
      matrix:
        device:
          - "iPhone 12 Pro Max (14.4)"
      fail-fast: false
      # The type of machine to run the job on.
      # Contains a sequence of tasks.

    runs-on: macos-11
    steps:
      - name: "List all simulators"
        run: "xcrun instruments -s"
      - name: "Start Simulator"
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: "List devices"
        run: "flutter devices"
      - name: "List devices"
        run: "flutter pub get"
      - name: "Run Flutter Driver tests"
        run: "flutter test integration_test"
      - uses: erickzanardo/flutter-gh-pages@v6
